### ISSUE TITLE
ImportError: cannot import name 'DDIMScheduler' from 'diffusers' (unknown location)

### ISSUE THREAD

**Issue by wqw547243068** [windmaple/Gemma-Chinese-instruction-tuning#2]
参考 [Gemma中文指令微调(Colab GPU).ipynb](https://github.com/windmaple/Gemma-Chinese-instruction-tuning/blob/main/Gemma%E4%B8%AD%E6%96%87%E6%8C%87%E4%BB%A4%E5%BE%AE%E8%B0%83(Colab%20GPU).ipynb) 

环境：

```
pip list | grep -E "trl|peft"
peft                       0.7.1
trl                        0.7.10
```

执行到 LoRA 微调时，报错：

```sh
python ft_gemma_lora.py 
Traceback (most recent call last):
  File "ft_gemma_lora.py", line 13, in <module>
    from trl import setup_chat_format
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/trl/__init__.py", line 7, in <module>
    from .extras import BestOfNSampler
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/trl/models/__init__.py", line 30, in <module>
    from .modeling_sd_base import (
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/trl/models/modeling_sd_base.py", line 23, in <module>
    from diffusers import DDIMScheduler, StableDiffusionPipeline, UNet2DConditionModel
ImportError: cannot import name 'DDIMScheduler' from 'diffusers' (unknown location)
```

代码里跟sd没关系，为啥导入setup_chat_format还要加载diffusers?

**Comment by windmaple** [comment]
应该是trl引用了

pip install一下diffusers?
